-- PostgreSQL data model for the translation-memory platform.
-- Also executed on H2 (PostgreSQL compatibility mode) for tests.

CREATE TABLE IF NOT EXISTS language_profile (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20)  NOT NULL UNIQUE,
    case_rule  VARCHAR(20)  NOT NULL DEFAULT 'PRESERVE'  -- PRESERVE | LOWER | UPPER
);

CREATE TABLE IF NOT EXISTS term_mapping_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_lang     VARCHAR(20)  NOT NULL,
    target_lang     VARCHAR(20)  NOT NULL,
    product_line    VARCHAR(100) NOT NULL,
    source_term     VARCHAR(500) NOT NULL,
    approved_target VARCHAR(500) NOT NULL,
    replaced_target VARCHAR(500),
    polysemous      BOOLEAN      NOT NULL DEFAULT FALSE,
    alternatives    VARCHAR(2000),          -- ';' separated approved choices when polysemous
    note            VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS tm_version (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id        BIGINT,                                  -- lineage pointer, never rewritten
    label            VARCHAR(200) NOT NULL,
    status           VARCHAR(20)  NOT NULL,                   -- PUBLISHED | SUPERSEDED | ROLLBACK
    effective        BOOLEAN      NOT NULL DEFAULT FALSE,     -- exactly one row is effective
    checksum         VARCHAR(64)  NOT NULL,
    batch_manifest   TEXT,                                    -- JSON: batches folded into this version
    conflict_report  TEXT,                                    -- JSON: conflict handling records
    rollback_reason  VARCHAR(2000),
    download_url     VARCHAR(500),                            -- stable URL, kept for old versions
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tm_entry (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id    BIGINT       NOT NULL REFERENCES tm_version(id),
    source_lang   VARCHAR(20)  NOT NULL,
    target_lang   VARCHAR(20)  NOT NULL,
    product_line  VARCHAR(100) NOT NULL,
    source_text   TEXT         NOT NULL,
    target_text   TEXT         NOT NULL,
    origin_batch_id    BIGINT,
    origin_candidate_id BIGINT
);
CREATE INDEX IF NOT EXISTS idx_entry_version ON tm_entry(version_id);

CREATE TABLE IF NOT EXISTS import_batch (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key    VARCHAR(600) NOT NULL UNIQUE,          -- vendor|langs|line|fingerprint
    source_version_id  BIGINT,                                -- baseline TM version
    source_lang        VARCHAR(20)  NOT NULL,
    target_lang        VARCHAR(20)  NOT NULL,
    product_line       VARCHAR(100) NOT NULL,
    vendor             VARCHAR(100) NOT NULL,
    tmx_fingerprint    VARCHAR(64)  NOT NULL,
    mapping_rules      TEXT,                                  -- JSON snapshot of applied term rules
    status             VARCHAR(20)  NOT NULL,                 -- RECEIVED | REVIEWING | MIGRATING | COMPLETED
    total_candidates   INT          NOT NULL DEFAULT 0,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conflict_group (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_hash     VARCHAR(64)  NOT NULL,
    source_lang     VARCHAR(20)  NOT NULL,
    target_lang     VARCHAR(20)  NOT NULL,
    product_line    VARCHAR(100) NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'OPEN',     -- OPEN | RESOLVED
    resolved_candidate_id BIGINT
);

CREATE TABLE IF NOT EXISTS batch_candidate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id        BIGINT       NOT NULL REFERENCES import_batch(id),
    source_lang     VARCHAR(20)  NOT NULL,
    target_lang     VARCHAR(20)  NOT NULL,
    product_line    VARCHAR(100) NOT NULL,
    source_text     TEXT         NOT NULL,
    target_text     TEXT         NOT NULL,
    source_hash     VARCHAR(64)  NOT NULL,
    status          VARCHAR(20)  NOT NULL,                    -- PENDING | CONFLICT | BLOCKED | ACCEPTED | REJECTED | MIGRATED
    placeholder_sig VARCHAR(2000),
    anomaly_type    VARCHAR(40),                              -- PLACEHOLDER_MISMATCH | CASE_VIOLATION | POLYSEMOUS_TERM
    anomaly_detail  VARCHAR(2000),
    conflict_group_id BIGINT REFERENCES conflict_group(id),
    term_override   VARCHAR(500),
    decided_by      VARCHAR(100),
    decided_at      TIMESTAMP,
    version         BIGINT       NOT NULL DEFAULT 0,          -- optimistic lock for concurrent reviewers
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_candidate_batch_source UNIQUE (batch_id, source_hash)
);
CREATE INDEX IF NOT EXISTS idx_candidate_batch ON batch_candidate(batch_id);
CREATE INDEX IF NOT EXISTS idx_candidate_conflict ON batch_candidate(source_lang, target_lang, product_line, source_hash);

CREATE TABLE IF NOT EXISTS review_decision (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id    BIGINT       NOT NULL UNIQUE REFERENCES batch_candidate(id), -- one effective decision per candidate
    reviewer        VARCHAR(100) NOT NULL,
    action          VARCHAR(20)  NOT NULL,                    -- ACCEPT | REJECT | RESOLVE
    term_override   VARCHAR(500),
    corrected_target TEXT,
    reason          VARCHAR(2000),
    prior_version   BIGINT       NOT NULL,                    -- candidate.version before this decision
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS migration_task (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id          BIGINT       NOT NULL REFERENCES import_batch(id),
    status            VARCHAR(20)  NOT NULL,                  -- PENDING | RUNNING | PAUSED | FAILED | COMPLETED
    checkpoint_candidate_id BIGINT NOT NULL DEFAULT 0,        -- resume cursor: last committed candidate id
    processed_count   INT          NOT NULL DEFAULT 0,
    committed_count   INT          NOT NULL DEFAULT 0,
    skipped_count     INT          NOT NULL DEFAULT 0,
    error             VARCHAR(2000),
    version           BIGINT       NOT NULL DEFAULT 0,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS migration_commit (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      BIGINT    NOT NULL REFERENCES migration_task(id),
    batch_id     BIGINT    NOT NULL,
    candidate_id BIGINT    NOT NULL UNIQUE,                   -- a candidate is committed at most once, ever
    committed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_commit_task ON migration_commit(task_id);

CREATE TABLE IF NOT EXISTS task_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT       NOT NULL REFERENCES migration_task(id),
    from_status VARCHAR(20),
    to_status   VARCHAR(20)  NOT NULL,
    message     VARCHAR(2000),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_event_task ON task_event(task_id);

CREATE TABLE IF NOT EXISTS upload_session (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_key   VARCHAR(200) NOT NULL UNIQUE,                -- idempotency key supplied by the uploader
    vendor       VARCHAR(100) NOT NULL,
    source_lang  VARCHAR(20)  NOT NULL,
    target_lang  VARCHAR(20)  NOT NULL,
    product_line VARCHAR(100) NOT NULL,
    total_chunks INT          NOT NULL,
    fingerprint  VARCHAR(64)  NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'OPEN',        -- OPEN | COMPLETED
    batch_id     BIGINT,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS upload_chunk (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT NOT NULL REFERENCES upload_session(id),
    chunk_index INT    NOT NULL,
    data        TEXT   NOT NULL,
    CONSTRAINT uq_chunk_session_index UNIQUE (session_id, chunk_index)  -- duplicate shards are absorbed
);
